BlogApp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("blog.urls")),
    path("", include("users.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

blog/urls.py
from django.urls import path
from .views import HomeView, PostDeleteView, PostDetailView, PostCreateView, PostUpdateView, AuthorPostsListView,filterPost, introView

app_name="blog"

urlpatterns = [
    path("", introView, name="intro"),
    path("posts/", HomeView.as_view(), name="home"),
    path("author/<int:pk>/", AuthorPostsListView.as_view(), name="post-author"),
    path("<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("add/", PostCreateView.as_view(), name="post-create"),
    path("<int:pk>/update/", PostUpdateView.as_view(), name="post-update"),
    path("<int:pk>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path("filter/", filterPost, name="filter"),

]

users/urls.py
from django.urls import path
import users.views as userViews

app_name="users"

urlpatterns = [
    path("register/", userViews.register, name="register"),
    path("login/", userViews.LoginView.as_view(), name="login"),
    path("logout/", userViews.LogoutView.as_view(), name="logout"),
    path("profile/", userViews.profile, name="profile"),
]

blog/models.py
from django.db import models
from django.urls.base import reverse
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

class Post(models.Model):
    title = models.CharField(max_length=100)
    article = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    postImage = models.ImageField(default="placeholder.jpg", upload_to="postImages")
    publishedAt = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:home")

users/models.py
from django.contrib.auth.models import User
from django.db import models
from PIL import Image

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="profile.jpg", upload_to="profilePictures")

    def __str__(self) -> str:
        return f"{self.user.first_name} {self.user.last_name} Profile"

    def save(self):
        super().save()

        image = Image.open(self.image.path)
        if image.height > 300 or image.width > 300:
            image.thumbnail((300,300))
            image.save(self.image.path)

users/forms.py
from users.models import Profile
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=100)

    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "email", "password1", "password2"]

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(max_length=100)

    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "email"]

class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ["image"]

blog/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Post, Author
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

# Create your views here.

def introView(request):
    return render(request, "blog/intro.html", {})

class HomeView(ListView):
    template_name= "blog/home.html"
    context_object_name = "posts"
    ordering = ["-publishedAt"]
    paginate_by = 2

    def get_queryset(self):
        return Post.objects.all()

class AuthorPostsListView(ListView):
    model = Post
    template_name = "blog/author_post.html"
    context_object_name = "posts"
    paginate_by = 3
    
    def get_queryset(self):
        authorId = self.kwargs.get("pk")
        return Post.objects.filter(author_id = authorId).order_by("-publishedAt")

class PostDetailView(DetailView):
    model = Post
    template_name = "blog/detail.html"

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ["title", "article", "postImage"]

    def form_valid(self, form):
        form.instance.author = Author.objects.get(user_id=self.request.user.id)
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ["title", "article", "postImage"]

    def form_valid(self,form):
        form.instance.author = Author.objects.get(user_id = self.request.user.id)
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user.id == post.author.user.id:
            return True
        return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = "blog/post_delete.html"
    success_url = "/"

    def test_func(self):
        post = self.get_object()

        if self.request.user.id == post.author.user.id:
            return True
        return False


def filterPost(request):
    filterType = request.GET["selected"]
    query = request.GET["searchInput"]
    
    if filterType == "author":
        if " " in query:
            [firstName, lastName] = query.split(" ")
            author = Author.objects.filter(user__first_name__icontains=firstName, user__last_name__icontains=lastName).first()
        else:
            author = Author.objects.filter(user__first_name__icontains=query).first()
        
        posts = Post.objects.filter(author = author)

    elif filterType == "title":
        posts = Post.objects.filter(title__icontains =query)
    else:
        posts = Post.objects.filter(article__icontains = query)

    return render(request, "blog/home.html", {"posts":posts})

users/views.py
from django.shortcuts import redirect, render
from django.urls.base import reverse
from django.contrib import messages
from users.forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    form = UserRegisterForm()

    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Account has been created! Welcome {username}")
            return redirect(reverse("blog:home"))
    else: 
        form = UserRegisterForm()

    return render(request, "users/register.html", {"form": form})


class LoginView(LoginView):
    template_name = "users/login.html"

class LogoutView(LogoutView):
    template_name = "users/logout.html"

@login_required
def profile(request):
    if request.method == "POST":
        userForm = UserUpdateForm(request.POST, instance=request.user)
        profileForm = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if userForm.is_valid() and profileForm.is_valid():
            userForm.save()
            profileForm.save()
            messages.success(request, "Your account has been updated")
            return redirect("users:profile")

    else:
        userForm = UserUpdateForm(instance=request.user)
        profileForm = ProfileUpdateForm(instance= request.user.profile)
    
    context = {
        "userForm" : userForm,
        "profileForm" : profileForm
    }

    return render(request, "users/profile.html", context)

blog/templates/blog/author_post.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container mt-3" style="height: 100vh;">
        <div class="row">
            <div class="col-8">
    
                {% if posts %}
                    <h3 style="margin-top: 20px; margin-bottom: 10px; text-align: center;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                          </svg> Search Results
                    </h3>
                    <h5 style="margin-top: 10px; margin-bottom: 20px; text-align: center;">
                        {{page_obj.paginator.count}} Post{{page_obj.paginator.count|pluralize}} listed
    
                    </h5>
                    {% for post in posts %}
            
                        <div class="card w-100 mb-3" style="width: 18rem;">
                    
                            <div class="card-body">
                              <h5 class="card-title">{{ post.title }}</h5>
                              <footer class="blockquote-footer mt-2"><cite title="Source Title"><a href="{% url 'blog:post-author' post.author.id %}">{{post.author}}</a> </cite></footer>
                              <p class="card-text">{{ post.article }}</p>
                              <a href="{% url 'blog:post-detail' post.id %}" class="btn btn-primary">Read Detail</a>
                            </div>
                            <div class="card-footer text-muted">
                                {{post.publishedAt}}
                            </div>
                        </div>
               
                    {% endfor %}
                {% endif %}
            </div>
    
            <div class="col-4">
                <div class="mb-3">
                    <div class="card">
                        <div class="card-header">
                            <h5>Filter Posts</h5>
    
                        </div>
                        <div class="card-body">
                            <select class="form-select" aria-label="Default select example">
                                <option value="author">Author</option>
                                <option value="title">Title</option>
                                <option value="publishedDay">Published Day</option>
                              </select>
    
                              <div class="mb-3 mt-3">
                                <label for="exampleDropdownFormPassword2" class="form-label"> <b> Search</b></label>
                                <input type="search" class="form-control" id="exampleDropdownFormPassword2" placeholder="Search">
                                </div>
                                <button type="submit" class="btn btn-primary">Filter</button>
                        </div>
                  
                    </div>
                </div>
              
                   
            </div>
        </div>
    
        {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
    
                    {% for page in page_obj.paginator.page_range %}
    
                        {% if page_obj.number == page %}
                            <li class="page-item active"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
    
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
    
                        {% endif %}
                        
                    {% endfor %}
                    <li class="page-item"><a class="page-link" href="#">Next</a></li>
                </ul>
            </nav>
    
    
        {% endif %}
    
    </div>
    


{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/base.css' %}">

    <title>Home</title>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark" style="background: rgb(2,0,36);
  background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(212,12,187,1) 100%, rgba(0,212,255,1) 100%);">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blog:intro' %}">Blog App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'blog:home' %}">Posts</a>
            </li>
          </ul>
          <form class="d-flex">
              {% if user.is_authenticated %}
                  <a class="nav-link active text-light" aria-current="page" href="{% url 'blog:post-create' %}">Create Post</a>
                  <div class="dropdown">
                    <a class="btn btn-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                      <img src="{{ user.profile.image.url }}" class="rounded-circle" width="28" height="32" alt=""> {{ user.first_name }} {{user.last_name}}
                    </a>
                  
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                      <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>
                      <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                    </ul>
                  </div>
              {% else %}
                  <a class="nav-link text-light" href="{% url 'users:login' %}">Login</a>
                  <a class="nav-link text-light" href="{% url 'users:register' %}">Register</a>
              {% endif %}
              
          </form>
        </div>
      </div>
    </nav>  


  
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}}">
            {{message}}
          </div>
        {% endfor %}
      {% endif %}
      {% block content %}
  
      {% endblock %}


    <section class="p-5 bg-dark text-white text-center" style="background: rgb(2,0,36);
    background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(212,12,187,1) 100%, rgba(0,212,255,1) 100%);">
      <div class="container">
          <div class="row justify-content-between align-items-center">
              <div class="col-6">
                  <h5>About Us</h5>
                  <p class="py-3">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque inventore assumenda, quas minima, sequi adipisci quae in harum tenetur illo at nesciunt laboriosam? Cum, aliquam.</p>
              </div>
              <div class="col-6">
                  <h5>Community</h5>
              
                  <p class="py-3">
                      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio eaque, sunt, esse earum quos quia nobis excepturi accusantium dignissimos, error laboriosam corrupti commodi! Sit impedit a saepe itaque reprehenderit architecto!
                  </p>
              </div>
          </div>
          <p class="lead mt-4">
              Copyright &copy; 2021
          </p>
      </div>
  </section>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

</body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container mt-3" style="height: 100vh;">

        <div class="detail-title">
            <div class="row">
                <div class="col-10">
                    <h3>
                        {{post.title}}
                    </h3>
                </div>
                <div class="col-2">
                    {% if object.author.user == user %}
                        <a class="btn btn-primary" href="{% url 'blog:post-update' post.id %}">Update</a>
                        <a class="btn btn-secondary" href="{% url 'blog:post-delete' post.id %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                            </svg>
                        </a>
                    {% endif %}
                </div>
            </div>
            
        </div>
        <hr>
    
        <p id="published">{{post.publishedAt}}</p>
        <div class="text-center">
            <img src="{{ post.postImage.url }}" alt="no image">
    
        </div>
    
        <div class="detail-article">
            {{post.article}}
        </div>
        <p id="author"><b> {{post.author}}</b> </p>
        
    </div>


{% endblock %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container mt-3" style="height: 100vh;">
        
        <div class="row">
            <div class="col-8">
    
                {% if posts %}
                    {% for post in posts %}
            
                        <div class="card w-100 mb-3" style="width: 18rem;">
                            <div class="card-body">
                              <h5 class="card-title">{{ post.title }}</h5>
                              <footer class="blockquote-footer mt-2"><cite title="Source Title"><a href="{% url 'blog:post-author' post.author.id %}">{{post.author}}</a> </cite></footer>
                              <p class="card-text">{{ post.article }}</p>
                              <a href="{% url 'blog:post-detail' post.id %}" class="btn btn-primary">Read Detail</a>
                            </div>
                            <div class="card-footer text-muted">
                                {{post.publishedAt}}
                            </div>
                        </div>
               
                    {% endfor %}
                {% endif %}
            </div>
    
            <div class="col-4">
                <div class="mb-3">
                    <div class="card">
                        <div class="card-header">
                            <h5>Filter Posts</h5>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'blog:filter' %}">
    
                                {% csrf_token %}
                                
                                <select class="form-select" name="selected" aria-label="Default select example">
                                    <option value="author">Author</option>
                                    <option value="title">Title</option>
                                    <option value="article">Article</option>
                                </select>
        
                                <div class="mb-3 mt-3">
                                    <label for="exampleDropdownFormPassword2" class="form-label"> <b> Search</b></label>
                                    <input type="search" class="form-control" id="exampleDropdownFormPassword2" name="searchInput" placeholder="Search">
                                </div>
                                <button type="submit" class="btn btn-primary">Filter</button>
    
                            </form>
                        </div>
                  
                    </div>
                </div>
                
                    
                   
            </div>
        </div>
    
        {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
    
                    {% for page in page_obj.paginator.page_range %}
    
                        {% if page_obj.number == page %}
                            <li class="page-item active"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
    
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
    
                        {% endif %}
                        
                    {% endfor %}
                    <li class="page-item"><a class="page-link" href="#">Next</a></li>
                </ul>
            </nav>
    
    
        {% endif %}
    
    
    </div>
    
{% endblock %}

blog/templates/blog/intro.html
{% extends 'blog/base.html' %}

{% block content %}

    <section class="text-light text-center" style="background: rgb(2,0,36);
        background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(212,12,187,1) 35%, rgba(0,212,255,1) 100%);">

        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="col-md-6">
                    <h1 class="p-4">  <span class="text-warning">Blog</span>-App</h1>
                    <p class="lead my-3">
                        Create an account for free and share your ideas with people. Or, read other people articles and communicate them.
                    </p>
                    <a href="{% url 'blog:home' %}" class="btn btn-primary my-2 mx-2 btn-lg">Explore</a>
                    <a href="{% url 'users:register' %}" class="btn btn-primary my-2 btn-lg">Register Now </a> 

                   

                </div>
                <div class="col-md-6">
                    <img src="../../../media/backgrounds/blog.svg" alt="" class="img-fluid">

                </div>
            </div>
                
        </div>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
            <path fill="#fff" fill-opacity="1" d="M0,224L48,218.7C96,213,192,203,288,192C384,181,480,171,576,186.7C672,203,768,245,864,266.7C960,288,1056,288,1152,272C1248,256,1344,224,1392,208L1440,192L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z">

            </path>
        </svg>
    </section>

{% endblock %}

blog/templates/blog/post_delete.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container mt-3" style="height: 100vh;">
        <div class="card w-50 mx-auto">
            <div class="card-header mt-2">
                <h3 style="text-align: center;">Delete Post</h3>
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    <h4>Are you sure to delete the post?</h4>
        
                    <div>
                        <button class="btn btn-outline-danger mt-3">Delete</button>
                        <a class="btn btn-outline-secondary mt-3" href="{% url 'blog:post-detail' object.id %}">Cancel</a>
                    </div>
                    
                </form>
        
            </div>
        
        </div>
    </div>

{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container mt-3" style="height: 100vh;">
        <div class="card w-50 mx-auto">
            <div class="card-header mt-2">
                <h3 style="text-align: center;">Post</h3>
            </div>
            <div class="card-body">
    
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form|crispy}}
                    <div>
                        <button class="btn btn-primary mt-3">Post</button>
                    </div>
    
                </form>
    
            </div>
            {{u_form}}
        </div>

    </div>

{% endblock %}

users/templates/users/login.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container mt-3" style="height: 100vh;">
    
        <div class="card w-50 mx-auto">
            <div class="card-header mt-2">
                <h3 style="text-align: center;">Login</h3>
            </div>
            <div class="card-body">
    
                <form method="POST">
                    {% csrf_token %}
                    {{form|crispy }}
    
                    <div>
                        <button class="btn btn-primary mt-3 mb-3">Login</button>
                    </div>
    
                    <div>
                        <small>
                            Don't have an account? <a href="{% url 'users:register' %}">Register Now</a>
                        </small>
                    </div>
                    
                </form>
    
            </div>
    
        </div>
    </div>    

{% endblock %}

users/templates/users/logout.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container mt-3" style="height: 100vh;">
    
        <h3>You have been logged out</h3>
        <a href="{% url 'users:login' %}">Login Again?</a>
    
    </div>    
{% endblock %}

users/templates/users/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container mt-3" style="height: 100vh;">
        <div class="card w-50 mx-auto">
            <div class="card-header mt-2">
                <h3 style="text-align: center;">{{user.profile}}</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-4">
                        <img src="{{user.profile.image.url}}" class="rounded img-thumbnail" alt="no-image">
                    </div>
                    <div class="col-8">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{userForm|crispy}}
                            {{profileForm|crispy}}
                            <div>
                                <button type="submit" class="btn btn-primary" style="margin-top: 20px;">
                                    Update Profile
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
                
            </div>
    
        </div>
        
    </div>    



{% endblock %}

users/templates/users/register.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container mt-3" style="height: 100vh;">
        <div class="card w-50 mx-auto">
            <div class="card-header mt-2">
                <h3 style="text-align: center;">Register Now</h3>
            </div>
            <div class="card-body">
    
                <form method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
    
                    <div>
                        <button class="btn btn-primary mt-3">Register</button>
                    </div>
                    
                </form>
    
            </div>
    
        </div>
        
    </div>    


{% endblock %}